server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  # standalone mode
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  application:
    name: discovery-service
  profiles: docker

eureka:
  instance:
    hostname: discovery-service
    prefer-ip-address: false
  # standalone mode
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
